version: '3.3'
services:
  actualteller:
    image: freddyabrego/actualteller:latest
    #build: https://git.local/freddyabrego/actualTeller
    container_name: actualteller
    volumes:
      - './data:/data'
    ports:
      - '5000:5000'
    restart: 'on-failure'